# This is a basic workflow to help you get started with Actions

name: Metrix Dvora 2 GO :)

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - '.github/workflows/docker-image.yml'
      - './docs/*'
      - 'history.txt'
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  theMatrix:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        jdk: [8, 11, 14]
    runs-on: ${{ matrix.os }}
    env:
      JDK_VERSION:  ${{ matrix.jdk }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        
      - name: Get Public IPv4
        shell: pwsh
        run: Invoke-RestMethod 'https://api.ipify.org?format=json'

      - name: Get local IPv4
        shell: pwsh
        run: Get-NetIPConfiguration | select InterfaceAlias,IPv4Address
